### PR TITLE
Add local data storage and recipe display functionality

### PR DESCRIPTION
**Pull request by Jddg95**
Details:

Local Data Storage: Implemented code within the `requestWeather` and `requestRecipes` functions to store fetched weather and recipe data locally using the `localStorage` API. This optimization reduces reliance on external API calls, improving performance and enabling offline access to previously retrieved data.

DisplayRecipes Functionality: Introduced the `displayRecipes` function, which dynamically renders fetched recipe data on the webpage. This function organizes recipes into two separate sections and presents them in a visually appealing grid-like format for enhanced user experience.

Event Listener for "Get Recipes" Button: Added an event listener for the "Get Recipes" button, triggering the `displayRecipes` function to display stored recipe data from local storage. This feature streamlines access to recipe content, providing users with quick and convenient access to previously fetched recipes.

Impact:

Optimized Performance: By storing weather and recipe data locally, the application reduces the need for repeated API calls, resulting in faster load times and improved responsiveness.

Enhanced Offline Capabilities: Users can access previously fetched weather and recipe data even when offline, ensuring continuity in functionality regardless of network availability.

Improved User Interface: The addition of the `displayRecipes` function and the event listener for the "Get Recipes" button enhances the presentation of recipe data on the webpage, providing users with a more intuitive and visually pleasing browsing experience.

### CODE REVIEW

**Review by IvoryRines — CHANGES_REQUESTED** [review]
-It appears that you didn't pull after Stephen's modal was merged onto the main branch Tuesday. If I were to approve your pull request as it is now, it would remove Stephen's work.
-Also, the event listener for the submit button already exists at the very bottom of the js and is functional. With the if/else statement I have created, the weather dependent recipes already log automatically to the console when a zip code is entered and the submit button is pressed. Therefore, they should also display automatically with your function .The same is true for Stephen's modal... when you enter a zip-code and press the apply button on the modal it automatically logs the weather dependent recipes to the console. This being true, we can now remove the get recipes button as we discussed, so it no longer needs an event listener.
-Could you please stash your changes, pull the up-to-date version of the repository, apply the stash, and then commit again? 
-I will push my changes now, because I think it will be helpful if you merge my if/else statement first. That way, when you pull, you will get both Stephen's modal, as well as the if/else functionality. That will allow you to add your function and test it with both the apply button in the modal and the submit button above the weather dashboard.

**Comment by IvoryRines** [comment]
I forgot to mention, you don't need to worry about the recipes not displaying 3 over 3, because Robby has already created the framework that your function will populate. If it would be helpful, you could ask him if he's ready to push and then you could tie everything together all at once.

**Review by Jddg95 — COMMENTED** [review]
Done

**Review by IvoryRines — APPROVED** [review]
Looks perfect! Great Job!

**Pull request merged**
